#include "../headers/main.h"

#define MAX_ITER 100

/*
    Expection-Maximization Clustering Algorithm

    Usage: ./program <dataset_file> <metadata_file> [output_labels_file]
    TODO: fix all the missing updates
*/
int main(int argc, char **argv) { 
    Metadata metadata;                  // Contains number of samples, number of features, number of clusters and max line size
    
    double *X = NULL;                   // X[N * D] Vector of data points
    
    ClusterParams cluster_params;       // Cluster parameters: mu (D * K), sigma (D * K), pi (K)
    double *gamma = NULL;               // gamma[N * K] Responsibilities vector, gamma[i * K + k] is the probability that data point i was generated by cluster k 
    
    double *N_k = NULL;                 // N_k[k] = Sum of responsibilities per cluster
    double *mu_k = NULL;                // mu_k[k * D] = Weighted sums for means
    double *sigma_k = NULL;             // sigma_k[k * D] = Weighted sums for variances

    int *predicted_labels = NULL;       // Predicted cluster labels
    int *ground_truth_labels = NULL;    // Ground truth labels

    // Check command line arguments
    InputParams_t inputParams;
    if (parseParameter(argc, argv, &inputParams) != 0) {
        fprintf(stderr, "Error parsing input parameters.\n");
        return 1;
    }

    // Read metadata from metadata file into Metadata struct
    int meta_status = read_metadata(inputParams.metadata_filename, &metadata);
    if(meta_status != 0){
        fprintf(stderr, "Failed to read metadata from file: %s\n", inputParams.metadata_filename);
        return 1;
    }
    printf("Metadata: samples N=%d, features D=%d, clusters K=%d\n", metadata.N, metadata.D, metadata.K);
    
    // Allocate buffers
    X = malloc(metadata.N * metadata.D * sizeof(double));
    predicted_labels = malloc(metadata.N * sizeof(int));
    ground_truth_labels = malloc(metadata.N * sizeof(int));
    int cluster_alloc_status = alloc_cluster_params(&cluster_params, &metadata);
    gamma = malloc(metadata.N * metadata.K * sizeof(double));
    N_k = malloc((size_t)metadata.K * sizeof(double));              
    mu_k = malloc((size_t)metadata.K * metadata.D * sizeof(double));   
    sigma_k = malloc((size_t)metadata.K * metadata.D * sizeof(double));     

    // Check that all allocations were successful
    if(!X || !predicted_labels || !ground_truth_labels || cluster_alloc_status != 0 || !gamma || !N_k || !mu_k || !sigma_k){
        fprintf(stderr, "Memory allocation failed\n");
        safe_cleanup(&X,&predicted_labels,&ground_truth_labels,&cluster_params,&gamma,&N_k,&mu_k,&sigma_k);
        return 1;
    }   

    // Read dataset
    if(read_dataset(inputParams.dataset_filename, &metadata, X, ground_truth_labels) != 0){
        fprintf(stderr, "Failed to read dataset from file: %s\n", inputParams.dataset_filename);
        safe_cleanup(&X,&predicted_labels,&ground_truth_labels,&cluster_params,&gamma,&N_k,&mu_k,&sigma_k);
        return 1;
    }
    

    // Initialize parameters
    init_params(X, &metadata, &cluster_params);
    
    /*
        EM loop
        The loop runs until MAX_ITER is reached
    */
    for (int iter = 0; iter < MAX_ITER; iter++) {
        // E-step
        e_step(X, metadata.N, &metadata, &cluster_params, gamma);

        // M-step
        m_step(X, &metadata, gamma,  &cluster_params, N_k, mu_k, sigma_k);
    }
    
    // Compute predicted labels from responsibilities
    compute_clustering(gamma, metadata.N, metadata.K, predicted_labels);    
    // Print final parameters 
    debug_print_cluster_params(&metadata, &cluster_params);

    // Write final cluster assignments to file to validate
    if (inputParams.output_filename){
        int write_status = write_labels_info(inputParams.output_filename, predicted_labels, ground_truth_labels, metadata.N);
        if(write_status != 0){
            fprintf(stderr, "Failed to write labels to file: %s\n", inputParams.output_filename);
        }
    }
    
    // Free all the allocated memory
    safe_cleanup(&X,&predicted_labels,&ground_truth_labels,&cluster_params,&gamma,&N_k,&mu_k,&sigma_k);
    return 0;
}
