#include "../headers/main.h"

#define MAX_ITER 100

/*
    Expection-Maximization Clustering Algorithm

    Usage: ./program <dataset_file> <metadata_file> <execution_info_file> [output_labels_file]
*/
int main(int argc, char **argv) { 
    Metadata metadata;                  // Contains number of samples, number of features, number of clusters and max line size
    
    double *X = NULL;                   // X[N * D] Vector of data points
    
    ClusterParams cluster_params;       // Cluster parameters: mu (D * K), sigma (D * K), pi (K)
    double *gamma = NULL;               // gamma[N * K] Responsibilities vector, gamma[i * K + k] is the probability that data point i was generated by cluster k 

    Accumulators cluster_acc;           // Contains accumulators for m-step: N_k (K), mu_k (D * K), sigma_k (D * K)

    int *predicted_labels = NULL;       // Predicted cluster labels
    int *ground_truth_labels = NULL;    // Ground truth labels

    // Check command line arguments
    InputParams_t inputParams;
    if (parseParameter(argc, argv, &inputParams) != 0) {
        fprintf(stderr, "Error parsing input parameters.\n");
        return 1;
    }

    // Read metadata from metadata file into Metadata struct
    int meta_status = read_metadata(inputParams.meta_data_file_path, &metadata);
    if(meta_status != 0){
        fprintf(stderr, "Failed to read metadata from file: %s\n", inputParams.meta_data_file_path);
        return 1;
    }
    printf("Metadata: samples N=%d, features D=%d, clusters K=%d\n", metadata.N, metadata.D, metadata.K);
    
    // Allocate buffers
    int cluster_alloc_status = alloc_cluster_params(&cluster_params, &metadata);
    int acc_alloc_status =  alloc_accumulators(&cluster_acc, &metadata);
    X = malloc(metadata.N * metadata.D * sizeof(double));
    predicted_labels = malloc(metadata.N * sizeof(int));
    ground_truth_labels = malloc(metadata.N * sizeof(int));
    gamma = malloc(metadata.N * metadata.K * sizeof(double));
       
    // Check that all allocations were successful
    if(!X || !predicted_labels || !ground_truth_labels || !gamma || cluster_alloc_status != 0 || acc_alloc_status != 0){
        fprintf(stderr, "Memory allocation failed\n");
        safe_cleanup(&cluster_params,&cluster_acc,&X,&predicted_labels,&ground_truth_labels,&gamma);
        return 1;
    }   

    // Read dataset
    if(read_dataset(inputParams.dataset_file_path, &metadata, X, ground_truth_labels) != 0){
        fprintf(stderr, "Failed to read dataset from file: %s\n", inputParams.dataset_file_path);
        safe_cleanup(&cluster_params,&cluster_acc,&X,&predicted_labels,&ground_truth_labels,&gamma);
        return 1;
    }
    
    // Initialize parameters
    init_params(X, &metadata, &cluster_params);
    
    // Log-likelihood variables for convergence check
    double prev_log_likelihood = -INFINITY;
    double curr_log_likelihood = 0.0;
    /*
        EM loop
        The loop runs until MAX_ITER is reached or convergence is achieved based on the threshold (if provided)
    */
    for (int iter = 0; iter < MAX_ITER; iter++) {
        // E-step
        e_step(X, metadata.N, &metadata, &cluster_params, gamma);

        // M-step
        m_step(X, &metadata, &cluster_params, &cluster_acc, gamma);

        // Compute log-likelihood for convergence check (if threshold is set)
        if (inputParams.threshold > 0.0) {
            if (check_convergence(prev_log_likelihood, &curr_log_likelihood, inputParams.threshold, X, &metadata, &cluster_params)) {
                debug_println("Convergence reached at iteration %d with log-likelihood: %.8lf", iter + 1, curr_log_likelihood);
                break;
            }
            prev_log_likelihood = curr_log_likelihood;
        }
    }
    
    // Compute predicted labels from responsibilities
    compute_clustering(gamma, metadata.N, metadata.K, predicted_labels);    
    // Print final parameters 
    debug_print_cluster_params(&metadata, &cluster_params);

    // Write final cluster assignments to file to validate
    if (inputParams.output_file_path){
        int write_status = write_labels_info(inputParams.output_file_path, X, predicted_labels, ground_truth_labels, &metadata, &cluster_params, MAX_ITER);
        if(write_status != 0){
            fprintf(stderr, "Failed to write labels to file: %s\n", inputParams.output_file_path);
        }
    }
    
    // Free all the allocated memory
    safe_cleanup(&cluster_params,&cluster_acc,&X,&predicted_labels,&ground_truth_labels,&gamma);
    return 0;
}
