#include "headers/main.h"

#define MAX_ITER 100

/*
    Expection-Maximization Clustering Algorithm

    Usage: ./program <dataset_file> <metadata_file> <execution_info_file> [output_labels_file]
*/
int main(int argc, char **argv) { 
    // Initialize MPI
    MPI_Init(&argc, &argv);
    // Id of the current process
    int rank;
    // Number of processes
    int size;
    
    MPI_Comm_rank(MPI_COMM_WORLD, &rank);
    MPI_Comm_size(MPI_COMM_WORLD, &size);


    int N;                              // Number of samples
    int D;                              // Number of features
    int K;                              // Number of clusters
    int max_line_size;                  // Maximum number of character in a line in the dataset file
    
    double *X = NULL;                   // X[N * D] Vector of data points
    double *mu = NULL;                  // mu[k * D] Vector of feature means per cluster; mu[k * D + d] is the mean of feature d for cluster k
    double *sigma = NULL;               // sigma[k * D] Vector of variance per each feature per cluster; sigma[k * D + d] is the variance of feature d for cluster k
    double *pi = NULL;                  // pi[k] Vector of mixture weights: prior probability that a random data point belongs to cluster k
    double *gamma = NULL;               // gamma[N * K] Responsibilities vector, gamma[i * K + k] is the probability that data point i was generated by cluster k 
    
    double *N_k = NULL;                 // N_k[k] = Sum of responsibilities per cluster
    double *mu_k = NULL;                // mu_k[k * D] = Weighted sums for means
    double *sigma_k = NULL;             // sigma_k[k * D] = Weighted sums for variances

    int *predicted_labels = NULL;       // Predicted cluster labels
    int *ground_truth_labels = NULL;    // Ground truth labels

    double start_time = MPI_Wtime();    
    double io_time = 0.0, compute_time = 0.0;

    // Check command line arguments
    if(argc < 4 || argc > 5){
        if (rank == 0) fprintf(stderr, "Usage: %s <dataset_file> <metadata_file> <execution_info_file> [output_labels_file]\n", argv[0]);
        MPI_Abort(MPI_COMM_WORLD,1);
    }
    if(argv[1] == NULL || argv[2] == NULL || argv[3] == NULL || (argc > 4 && argv[4] == NULL)){
        if (rank == 0) fprintf(stderr, "Dataset file, metadata and execution info file must be provided\n");
        MPI_Abort(MPI_COMM_WORLD,1);
    }


    // Get filenames from arguments
    const char *filename = argv[1];
    const char *metadata_filename = argv[2];
    const char *execution_info_filename = argv[3];
    const char *output_labels_file = (argc > 4) ? argv[4] : NULL;

    double io_start = MPI_Wtime();
    // Read metadata from metadata file (only by rank 0)
    if (rank == 0) {
        int meta_status = read_metadata(metadata_filename, &N, &D, &K, &max_line_size);
        if(meta_status != 0){
            fprintf(stderr, "Failed to read metadata from file: %s\n", metadata_filename);
            MPI_Abort(MPI_COMM_WORLD,1);
        }
        printf("Metadata: samples N=%d, features D=%d, clusters K=%d\n", N, D, K);
    }
    io_time += MPI_Wtime() - io_start;

    // TODO: Broadcast N, D, K to all process using a single MPI call
    MPI_Bcast(&N, 1, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(&D, 1, MPI_INT, 0, MPI_COMM_WORLD);
    MPI_Bcast(&K, 1, MPI_INT, 0, MPI_COMM_WORLD);
    
    //TODO: check that all these malloc are needed by all processes or just by process zero
    // Allocate buffers
    X = malloc(N * D * sizeof(double));
    predicted_labels = malloc(N * sizeof(int));
    ground_truth_labels = malloc(N * sizeof(int));
    mu = malloc(K * D * sizeof(double)); 
    sigma = malloc(K * D * sizeof(double)); 
    pi = malloc(K * sizeof(double));
    gamma = malloc(N * K * sizeof(double));
    N_k = malloc((size_t)K * sizeof(double));              
    mu_k = malloc((size_t)K * D * sizeof(double));   
    sigma_k = malloc((size_t)K * D * sizeof(double));     

    // Check that all allocations were successful
    if(!X || !predicted_labels || !ground_truth_labels || !mu || !sigma || !pi || !gamma || !N_k || !mu_k || !sigma_k){
        fprintf(stderr, "Memory allocation failed\n");
        safe_cleanup(&X,&predicted_labels,&ground_truth_labels,&mu,&sigma,&pi,&gamma,&N_k,&mu_k,&sigma_k);
        MPI_Abort(MPI_COMM_WORLD,1);
    }   

    // Read dataset (only by rank 0)
    io_start = MPI_Wtime();
    if(rank == 0){
        if(read_dataset(filename, D, N, max_line_size, X, ground_truth_labels) != 0){
            fprintf(stderr, "Failed to read dataset from file: %s\n", filename);
            safe_cleanup(&X,&predicted_labels,&ground_truth_labels,&mu,&sigma,&pi,&gamma,&N_k,&mu_k,&sigma_k);
            MPI_Abort(MPI_COMM_WORLD,1);
        }
    }
    io_time += MPI_Wtime() - io_start;

    double compute_start = MPI_Wtime();
    // Initialize parameters
    init_params(X, N, D, K, mu, sigma, pi);
    
    /*
        EM loop
        The loop runs until MAX_ITER is reached
    */
    for (int iter = 0; iter < MAX_ITER; iter++) {
        // E-step
        e_step(X, N, D, K, mu, sigma, pi, gamma);

        // M-step
        m_step(X, N, D, K, gamma,  mu, sigma, pi, N_k, mu_k, sigma_k);
    }
    
    // Compute predicted labels from responsibilities
    if (rank == 0) compute_predicted_labels(gamma, N, K, predicted_labels);    
    compute_time += MPI_Wtime() - compute_start;


    io_start = MPI_Wtime();
    if (rank == 0) {
        // Print final parameters 
        debug_print_cluster_params(K, D, mu, sigma, pi);

        // Write final cluster assignments to file to validate
        if (output_labels_file){
            int write_status = write_labels_info(output_labels_file, predicted_labels, ground_truth_labels, N);
            if(write_status != 0){
                fprintf(stderr, "Failed to write labels to file: %s\n", output_labels_file);
            }
        }
    }
    io_time += MPI_Wtime() - io_start;

    // Report the execution info (only by rank 0)
    if(rank == 0){
        if(write_execution_info(execution_info_filename, size, N, D, K, MPI_Wtime() - start_time, io_time, compute_time) != 0){
            fprintf(stderr, "Failed to write execution info to file\n");
            MPI_Abort(MPI_COMM_WORLD, 1);
        }
    }
    // Free all the allocated memory
    safe_cleanup(&X,&predicted_labels,&ground_truth_labels,&mu,&sigma,&pi,&gamma,&N_k,&mu_k,&sigma_k);
    return 0;
}
